### ISSUE TITLE
Requirement on Global Namespace

### ISSUE THREAD

**Issue by AugustNagro** [jokade/angulate2#29]
The facades in this project require angular at a global namespace, but can that be avoided? 

It's ideal to work with modules, and the RCs don't provide a namespace-polluting build file. I haven't found a way to get SystemJS to expose `ng`.

Would import sytax like [this](https://github.com/scala-js/scala-js/issues/2175) be required?

**Comment by jokade** [comment]
With the advent of 0.6.13, Scala,js now supports modules. I'm currently working on a major update that will solve this problem

**Comment by jokade** [comment]
The new `0.1-NSAPSHOT` now uses the CommonJS module format (requires Scala.js 0.6.13+).
