### ISSUE TITLE
Currently no published artifact?

### ISSUE THREAD

**Issue by n3phtys** [jokade/angulate2#31]
Trying to get the examples working once again, sbt cannot resolve some dependencies anymore.

As far as I see, the 0.1-SNAPSHOT cannot be resolved anymore as it does not appear to be within Sonatype. Will there be a new version published soon?

**Comment by jokade** [comment]
I've recently published the new 0.1-SNAPSHOT with Scala.js 0.6.13 module support and I'm currently reworking the entire codebasis.

**Comment by jokade** [comment]
The current artifact now is `0.0.1-SNAPSHOT`.
